name: .NET Test

on:
 push:
  branches:
   - master
 pull_request:

jobs:
 test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          src

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/ParquetViewer.sln

    - name: Build
      run: dotnet build src/ParquetViewer.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test src/ParquetViewer.sln --no-build --verbosity normal

    - name: Test Report
      uses: bibipkins/dotnet-test-reporter@v1.4.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-title: 'Unit Test Results'
        results-path: ./TestResults/*.trx
        coverage-path: ./TestResults/coverage.xml
        coverage-threshold: 80
