name: .NET Test

on:
 push:
  branches:
   - master
 pull_request:

jobs:
 test:
    runs-on: windows-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          src

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore src/ParquetViewer.sln

    - name: Build
      run: dotnet build src/ParquetViewer.sln --configuration Debug --no-restore

    - name: Test
      run: dotnet test src/ParquetViewer.sln --no-build --logger trx

    - name: Test Report
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      with:
        files: src/ParquetViewer.Tests/TestResults/*.trx
